spring: 
    profiles: 
        active: 
        - dev
---
spring: 
    profiles: dev
    application: 
        name: microservicecloud-config-zsh-dev
---        
spring: 
    profiles: test
    application: 
        name: microservicecloud-config-zsh-test